import { describe, expect, vi, test } from "vitest";
import {
  getWeatherData,
  formatWeatherData,
} from "../controller/weatherApiController";
import * as db from "../controller/dbController";

test("mock", async () => {
  const expected = 3;
  vi.mock("../controller/weatherApiController.ts", async () => {
    return {
      getWeatherData: async () => {
        return {
          queryCost: 1,
          latitude: 51.1408,
          longitude: 7.21705,
          resolvedAddress: "Wermelskirchen, Nordrhein-Westfalen, Deutschland",
          address: "Wermelskirchen",
          timezone: "Europe/Berlin",
          tzoffset: 2,
          days: [
            {
              datetime: "2023-03-30",
              datetimeEpoch: 1680127200,
              tempmax: 15.5,
              tempmin: 10,
              temp: 13.1,
              feelslikemax: 15.5,
              feelslikemin: 8.9,
              feelslike: 13,
              dew: 7.9,
              humidity: 71,
              precip: 7.8,
              precipprob: 100,
              precipcover: 66.67,
              preciptype: [Array],
              snow: 0,
              snowdepth: 0,
              windgust: 67.7,
              windspeed: 31.3,
              winddir: 217.5,
              pressure: 1008.1,
              cloudcover: 77.4,
              visibility: 14.4,
              solarradiation: 97.1,
              solarenergy: 8.4,
              uvindex: 4,
              severerisk: 10,
              sunrise: "07:12:06",
              sunriseEpoch: 1680153126,
              sunset: "20:00:19",
              sunsetEpoch: 1680199219,
              moonphase: 0.28,
              conditions: "Rain, Partially cloudy",
              description: "Partly cloudy throughout the day with rain.",
              icon: "rain",
              stations: [Array],
              source: "comb",
            },
          ],
          stations: {
            D2248: {
              distance: 33549,
              latitude: 50.999,
              longitude: 6.794,
              useCount: 0,
              id: "D2248",
              name: "DW2248 Pulheim DE",
              quality: 0,
              contribution: 0,
            },
            EDDK: {
              distance: 30325,
              latitude: 50.87,
              longitude: 7.17,
              useCount: 0,
              id: "EDDK",
              name: "EDDK",
              quality: 50,
              contribution: 0,
            },
            E0822: {
              distance: 22018,
              latitude: 50.955,
              longitude: 7.111,
              useCount: 0,
              id: "E0822",
              name: "EW0822 Cologne DE",
              quality: 0,
              contribution: 0,
            },
            EDDL: {
              distance: 34192,
              latitude: 51.28,
              longitude: 6.78,
              useCount: 0,
              id: "EDDL",
              name: "EDDL",
              quality: 50,
              contribution: 0,
            },
          },
          currentConditions: {
            datetime: "15:45:00",
            datetimeEpoch: 1680183900,
            temp: 13.6,
            feelslike: 13.6,
            humidity: 72.3,
            dew: 8.7,
            precip: 0,
            precipprob: 0,
            snow: 0,
            snowdepth: 0,
            preciptype: null,
            windgust: 51.8,
            windspeed: 28.6,
            winddir: 251,
            pressure: 1008.6,
            visibility: 10,
            cloudcover: 71.3,
            solarradiation: 126,
            solarenergy: 0.5,
            uvindex: 1,
            conditions: "Partially cloudy",
            icon: "partly-cloudy-day",
            stations: ["EDDK", "EDDL", "E0822"],
            source: "obs",
            sunrise: "07:12:06",
            sunriseEpoch: 1680153126,
            sunset: "20:00:19",
            sunsetEpoch: 1680199219,
            moonphase: 0.28,
          },
        };
      },
    };
  });

  const result = await getWeatherData("2023-03-12", "2023-03-13");
  expect(result).toEqual({
    queryCost: 1,
    latitude: 51.1408,
    longitude: 7.21705,
    resolvedAddress: "Wermelskirchen, Nordrhein-Westfalen, Deutschland",
    address: "Wermelskirchen",
    timezone: "Europe/Berlin",
    tzoffset: 2,
    days: [
      {
        datetime: "2023-03-30",
        datetimeEpoch: 1680127200,
        tempmax: 15.5,
        tempmin: 10,
        temp: 13.1,
        feelslikemax: 15.5,
        feelslikemin: 8.9,
        feelslike: 13,
        dew: 7.9,
        humidity: 71,
        precip: 7.8,
        precipprob: 100,
        precipcover: 66.67,
        preciptype: [Array],
        snow: 0,
        snowdepth: 0,
        windgust: 67.7,
        windspeed: 31.3,
        winddir: 217.5,
        pressure: 1008.1,
        cloudcover: 77.4,
        visibility: 14.4,
        solarradiation: 97.1,
        solarenergy: 8.4,
        uvindex: 4,
        severerisk: 10,
        sunrise: "07:12:06",
        sunriseEpoch: 1680153126,
        sunset: "20:00:19",
        sunsetEpoch: 1680199219,
        moonphase: 0.28,
        conditions: "Rain, Partially cloudy",
        description: "Partly cloudy throughout the day with rain.",
        icon: "rain",
        stations: [Array],
        source: "comb",
      },
    ],
    stations: {
      D2248: {
        distance: 33549,
        latitude: 50.999,
        longitude: 6.794,
        useCount: 0,
        id: "D2248",
        name: "DW2248 Pulheim DE",
        quality: 0,
        contribution: 0,
      },
      EDDK: {
        distance: 30325,
        latitude: 50.87,
        longitude: 7.17,
        useCount: 0,
        id: "EDDK",
        name: "EDDK",
        quality: 50,
        contribution: 0,
      },
      E0822: {
        distance: 22018,
        latitude: 50.955,
        longitude: 7.111,
        useCount: 0,
        id: "E0822",
        name: "EW0822 Cologne DE",
        quality: 0,
        contribution: 0,
      },
      EDDL: {
        distance: 34192,
        latitude: 51.28,
        longitude: 6.78,
        useCount: 0,
        id: "EDDL",
        name: "EDDL",
        quality: 50,
        contribution: 0,
      },
    },
    currentConditions: {
      datetime: "15:45:00",
      datetimeEpoch: 1680183900,
      temp: 13.6,
      feelslike: 13.6,
      humidity: 72.3,
      dew: 8.7,
      precip: 0,
      precipprob: 0,
      snow: 0,
      snowdepth: 0,
      preciptype: null,
      windgust: 51.8,
      windspeed: 28.6,
      winddir: 251,
      pressure: 1008.6,
      visibility: 10,
      cloudcover: 71.3,
      solarradiation: 126,
      solarenergy: 0.5,
      uvindex: 1,
      conditions: "Partially cloudy",
      icon: "partly-cloudy-day",
      stations: ["EDDK", "EDDL", "E0822"],
      source: "obs",
      sunrise: "07:12:06",
      sunriseEpoch: 1680153126,
      sunset: "20:00:19",
      sunsetEpoch: 1680199219,
      moonphase: 0.28,
    },
  });
});

// test('mock db', async() => {
//     const expected = await db.findUser('l@p')
//     vi.mock('../controller/dbController.ts', async() => {
//         return {
//             findUser: async()=> {
//                 return {
//                     User_ID: 3,
//                     Surname: 'lennart',
//                     Firstname: 'pafel',
//                     Email: 'l@p',
//                     Zipcode: 42929,
//                     Password: 'pafel',
//                     Created_at: new Date('2023-03-29T19:56:03.482Z'),
//                     Role: 'admin'
//                   }
//             }
//         }
//     })
//     expect

// })



test("mock2", async () => {
  vi.doUnmock("../controller/weatherApiController.ts");
  const expected = 3;
  vi.mock("../controller/weatherApiController.ts", async () => {
    const formatWeatherData = async () => {
      return {
        queryCost: 1,
        latitude: 51.1408,
        longitude: 7.21705,
        resolvedAddress: "Wermelskirchen, Nordrhein-Westfalen, Deutschland",
        address: "Wermelskirchen",
        timezone: "Europe/Berlin",
        tzoffset: 2,
        days: [
          {
            datetime: "2023-03-30",
            datetimeEpoch: 1680127200,
            tempmax: 15.5,
            tempmin: 10,
            temp: 13.1,
            feelslikemax: 15.5,
            feelslikemin: 8.9,
            feelslike: 13,
            dew: 7.9,
            humidity: 71,
            precip: 7.8,
            precipprob: 100,
            precipcover: 66.67,
            preciptype: [Array],
            snow: 0,
            snowdepth: 0,
            windgust: 67.7,
            windspeed: 31.3,
            winddir: 217.5,
            pressure: 1008.1,
            cloudcover: 77.4,
            visibility: 14.4,
            solarradiation: 97.1,
            solarenergy: 8.4,
            uvindex: 4,
            severerisk: 10,
            sunrise: "07:12:06",
            sunriseEpoch: 1680153126,
            sunset: "20:00:19",
            sunsetEpoch: 1680199219,
            moonphase: 0.28,
            conditions: "Rain, Partially cloudy",
            description: "Partly cloudy throughout the day with rain.",
            icon: "rain",
            stations: [Array],
            source: "comb",
          },
        ],
        stations: {
          D2248: {
            distance: 33549,
            latitude: 50.999,
            longitude: 6.794,
            useCount: 0,
            id: "D2248",
            name: "DW2248 Pulheim DE",
            quality: 0,
            contribution: 0,
          },
          EDDK: {
            distance: 30325,
            latitude: 50.87,
            longitude: 7.17,
            useCount: 0,
            id: "EDDK",
            name: "EDDK",
            quality: 50,
            contribution: 0,
          },
          E0822: {
            distance: 22018,
            latitude: 50.955,
            longitude: 7.111,
            useCount: 0,
            id: "E0822",
            name: "EW0822 Cologne DE",
            quality: 0,
            contribution: 0,
          },
          EDDL: {
            distance: 34192,
            latitude: 51.28,
            longitude: 6.78,
            useCount: 0,
            id: "EDDL",
            name: "EDDL",
            quality: 50,
            contribution: 0,
          },
        },
        currentConditions: {
          datetime: "15:45:00",
          datetimeEpoch: 1680183900,
          temp: 13.6,
          feelslike: 13.6,
          humidity: 72.3,
          dew: 8.7,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 51.8,
          windspeed: 28.6,
          winddir: 251,
          pressure: 1008.6,
          visibility: 10,
          cloudcover: 71.3,
          solarradiation: 126,
          solarenergy: 0.5,
          uvindex: 1,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-day",
          stations: ["EDDK", "EDDL", "E0822"],
          source: "obs",
          sunrise: "07:12:06",
          sunriseEpoch: 1680153126,
          sunset: "20:00:19",
          sunsetEpoch: 1680199219,
          moonphase: 0.28,
        },
      };
    };
    return { formatWeatherData };
  });

  const result = await formatWeatherData("2023-03-12", "2023-03-13");
  expect(result).toEqual({
    queryCost: 1,
    latitude: 51.1408,
    longitude: 7.21705,
    resolvedAddress: "Wermelskirchen, Nordrhein-Westfalen, Deutschland",
    address: "Wermelskirchen",
    timezone: "Europe/Berlin",
    tzoffset: 2,
    days: [
      {
        datetime: "2023-03-30",
        datetimeEpoch: 1680127200,
        tempmax: 15.5,
        tempmin: 10,
        temp: 13.1,
        feelslikemax: 15.5,
        feelslikemin: 8.9,
        feelslike: 13,
        dew: 7.9,
        humidity: 71,
        precip: 7.8,
        precipprob: 100,
        precipcover: 66.67,
        preciptype: [Array],
        snow: 0,
        snowdepth: 0,
        windgust: 67.7,
        windspeed: 31.3,
        winddir: 217.5,
        pressure: 1008.1,
        cloudcover: 77.4,
        visibility: 14.4,
        solarradiation: 97.1,
        solarenergy: 8.4,
        uvindex: 4,
        severerisk: 10,
        sunrise: "07:12:06",
        sunriseEpoch: 1680153126,
        sunset: "20:00:19",
        sunsetEpoch: 1680199219,
        moonphase: 0.28,
        conditions: "Rain, Partially cloudy",
        description: "Partly cloudy throughout the day with rain.",
        icon: "rain",
        stations: [Array],
        source: "comb",
      },
    ],
    stations: {
      D2248: {
        distance: 33549,
        latitude: 50.999,
        longitude: 6.794,
        useCount: 0,
        id: "D2248",
        name: "DW2248 Pulheim DE",
        quality: 0,
        contribution: 0,
      },
      EDDK: {
        distance: 30325,
        latitude: 50.87,
        longitude: 7.17,
        useCount: 0,
        id: "EDDK",
        name: "EDDK",
        quality: 50,
        contribution: 0,
      },
      E0822: {
        distance: 22018,
        latitude: 50.955,
        longitude: 7.111,
        useCount: 0,
        id: "E0822",
        name: "EW0822 Cologne DE",
        quality: 0,
        contribution: 0,
      },
      EDDL: {
        distance: 34192,
        latitude: 51.28,
        longitude: 6.78,
        useCount: 0,
        id: "EDDL",
        name: "EDDL",
        quality: 50,
        contribution: 0,
      },
    },
    currentConditions: {
      datetime: "15:45:00",
      datetimeEpoch: 1680183900,
      temp: 13.6,
      feelslike: 13.6,
      humidity: 72.3,
      dew: 8.7,
      precip: 0,
      precipprob: 0,
      snow: 0,
      snowdepth: 0,
      preciptype: null,
      windgust: 51.8,
      windspeed: 28.6,
      winddir: 251,
      pressure: 1008.6,
      visibility: 10,
      cloudcover: 71.3,
      solarradiation: 126,
      solarenergy: 0.5,
      uvindex: 1,
      conditions: "Partially cloudy",
      icon: "partly-cloudy-day",
      stations: ["EDDK", "EDDL", "E0822"],
      source: "obs",
      sunrise: "07:12:06",
      sunriseEpoch: 1680153126,
      sunset: "20:00:19",
      sunsetEpoch: 1680199219,
      moonphase: 0.28,
    },
  });
});
