services:
  wattwise:
    container_name: wattwise
    build: 
      context: .
      target: dev
    restart: always
    ports: 
      - 2000:8000
    volumes:
      - ./src:/app/src
      - ./schema.prisma:/app/schema.prisma
    command: npm run dev 
